name: Python format check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - ".github/workflows/python-format-check.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - ".github/workflows/python-format-check.yml"

jobs:
  code-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Black
        run: python -m pip install --upgrade pip black

      - name: Check formatting
        run: black --check .
